# Generated by Django 5.1.3 on 2024-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
