# Generated by Django 5.1.3 on 2024-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], max_length=92, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'SELLER')], max_length=150, null=True),
        ),
    ]
