# Generated by Django 5.1.3 on 2024-11-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_user_gender_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
    ]
